# Generated by Django 5.1.3 on 2024-12-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_portfolio_prospect_imageportfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageportfolio',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='images',
            field=models.ManyToManyField(blank=True, to='main.tag'),
        ),
    ]
