# Generated by Django 5.1.3 on 2024-12-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_imageportfolio_portfolio_portfolio_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='images',
            field=models.ManyToManyField(blank=True, to='main.imageportfolio'),
        ),
    ]
